// import vid1 from "../videos/Shineinme.mp4";
import vid1 from "../images/youtube.png";   
import img1 from "../images/github.png";

const videos = [
  {
    id: "1",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "2",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "3",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "4",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "5",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "6",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "7",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "8",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
  {
    id: "9",
    title: "Shine in Me",
    views: 120,
    duration: 3.45,
    vid: vid1,
    logo: img1,
    author: "Phil Driscoll",
    posted: "1 month ago",
  },
];

export default videos;
